/**
 * Croatian site configuration.
 * This is the only file that differs between installations.
 * Fork this file (and the public/ assets) to create a new country site.
 */
const siteConfig = {
  // Branding
  logo:        '/hrd-logo.png',
  logoAlt:     'Hrvatsko rodoslovno društvo “Pavao Ritter Vitezović”',
  societyUrl:  'https://www.rodoslovlje.hr',
  indexUrl:    null,
  contactEmail: 'rodoslovlje@rodoslovlje.hr',

  apiHost: 'indeks-api.rodoslovlje.hr',

  // Languages shown in the dropdown, ordered alphabetically by language name
  languages: ['de', 'en', 'hr', 'hu', 'it', 'sl'],

  // Preferred language when no saved preference or browser match is found
  defaultLang: 'hr',

  // Per-language overrides: site title and society name
  i18n: {
    en: { site_title: 'Croatian Genealogical Index',      society_name: 'Croatian Genealogy Society “Pavao Ritter Vitezović”' },
    sl: { site_title: 'Hrvaški rodoslovni indeks',        society_name: 'Hrvaško rodoslovno društvo “Pavao Ritter Vitezović”' },
    hr: { site_title: 'Hrvatski rodoslovni indeks',       society_name: 'Hrvatsko rodoslovno društvo “Pavao Ritter Vitezović”' },
    hu: { site_title: 'Horvát Genealógiai Index',         society_name: '”Pavao Ritter Vitezović” Horvát Genealógiai Társaság' },
    de: { site_title: 'Kroatischer Genealogischer Index', society_name: 'Kroatische Genealogische Gesellschaft “Pavao Ritter Vitezović”' },
    it: { site_title: 'Indice genealogico croato',        society_name: 'Società genealogica croata “Pavao Ritter Vitezović”' },
  },

  // Intro paragraphs shown on empty search tabs. Falls back to 'en' for missing languages.
  // Each entry: { text: string (HTML allowed), warning?: true }
  intro: {
    en: [
      { text: '<strong>The Croatian Genealogical Index</strong> is an archival collection of data on births, marriages and deaths in Croatia, which has been created from the collections of individual genealogists since the very beginning of the society\'s activities. In it, we can search for the names and surnames of the people we are researching to find out if someone else has already discovered and described them. The basic index contains, in addition to personal names, the dates and places of birth, marriage and death, as well as the surname of the data provider, which allows the researcher to make further contact, indicates the direction and often makes it possible to research in an indirectly discovered parish. The contact information of the donors is not published, but it will not be difficult to get to them through the <a href="https://www.rodoslovlje.hr" target="_blank" rel="noopener">Croatian Genealogy Society</a>.' },
      { text: 'The main <strong>Search</strong> tab returns query results from all parts of the collection: births, marriages, and deaths of historical figures in Croatia. The search engine allows for exact or approximate searches across all fields, as well as searching only for records with a link to the source documents (on <a href="https://www.familysearch.org/en/search/collection/2040054" target="_blank" rel="noopener">Croatia, Church Books, 1516-1994</a> on FamilySearch.org (sign-in required, free)).' },
      { text: 'The additional <strong>Birth</strong>, <strong>Family</strong>, and <strong>Death</strong> tabs allow searching by specific record types. All fields are available: name, surname, date and place of the event, and the surname of the genealogist-provider of these data.' },
      { text: 'The family index also includes parents who were never married or even never lived together, which can be valuable information for descendants or information seekers. For each family, you can also see the number of children. Hidden behind the number is a list of the children\'s names with their year of birth (where this data is available).' },
      { text: 'The query results can be sorted by any column. For a full view, the query window can be hidden. It is possible to export the results in the form of a CSV file. The site is also available in other languages.' },
      { text: 'The list of surnames, names, dates and places of birth, marriage and death is made from a merged file to which many genealogists, listed on the <a href="?t=contributors">Genealogists</a> page, have contributed the results of their work.' },
      { text: 'Warning! The Croatian Genealogical Index is for informational purposes only. The Croatian Genealogy Society "Pavao Ritter Vitezović" disclaims any responsibility for the accuracy of the submitted data. The society is a voluntary association of individuals who are developing a common source of knowledge of data from registers and other written and oral sources. The structure of the society allows anyone who has their own collection of genealogical data to contribute it to the common cumulative collection and index. No individual who has contributed data to the index, nor the Croatian Genealogy Society, can guarantee the accuracy of the data.', warning: true },
      { text: 'If you have your own family tree in the form of a database and would like to join the existing genealogists with the results of your work, please send your GEDCOM file (excluding data on living persons) by <a href="mailto:rodoslovlje@rodoslovlje.hr">email</a> to the administrator.' },
    ],
    sl: [
      { text: '<strong>Hrvatski rodoslovni indeks</strong> je arhivska zbirka podatkov o rojenih, poročenih in umrlih na Hrvaškem, ki nastaja iz zbirk posameznih rodoslovcev od samega začetka delovanja društva. V njej lahko iščemo imena in priimke oseb, ki jih raziskujemo, da ugotovimo, ali jih je morda že odkril in popisal kdo drug. Osnovni indeks vsebuje poleg osebnih imen datume in kraje rojstev, porok in smrti ter priimek dajalca podatkov, kar omogoča iskalcu nadaljnji stik, nakaže smer in marsikdaj sploh omogoči raziskovanje v posredno odkriti župniji. Kontaktni podatki dajalcev niso objavljeni, vendar do njih ne bo težko priti prek <a href="https://www.rodoslovlje.hr" target="_blank" rel="noopener">Hrvaškega rodoslovnega društva</a>.' },
      { text: 'Glavni zavihek <strong>Iskanje</strong> vrne rezultate poizvedbe po vseh delih zbirke: rojenih, poročenih in umrlih zgodovinskih oseb na Hrvaškem. Iskalnik omogoča točno ali približno iskanje po vseh poljih, pa tudi iskanje samo zapisov s povezavo do izvornih dokumentov (na <a href="https://www.familysearch.org/en/search/collection/2040054" target="_blank" rel="noopener">Croatia, Church Books, 1516-1994</a> na FamilySearch.org (potrebna je prijava, brezplačno)).' },
      { text: 'Dodatni zavihki <strong>Rojstvo</strong>, <strong>Družina</strong> in <strong>Smrt</strong> omogočajo iskanje po posameznem tipu zapisov. Na voljo so vsa polja: ime, priimek, datum in kraj dogodka ter priimek rodoslovca-dajalca podatkov.' },
      { text: 'Indeks družin vsebuje tudi starše, ki niso bili nikoli poročeni ali celo nikoli niso živeli skupaj, kar je lahko dragocen podatek za potomce oziroma iskalce informacij. Pri vsaki družini je viden tudi število otrok. Za številko se skriva seznam imen otrok z letnico rojstva (kjer ta podatek obstaja).' },
      { text: 'Rezultate poizvedbe je mogoče razvrstiti po katerem koli stolpcu. Za polni pregled je mogoče skriti poizvedbeno okno. Možen je izvoz rezultatov v obliki datoteke CSV. Za tuje uporabnike indeksa je stran na voljo tudi v angleščini.' },
      { text: 'Seznam priimkov, imen, datumov in krajev rojstev, porok in smrti je sestavljen iz združene datoteke, v katero so prispevali rezultate svojega dela številni rodoslovci, navedeni na strani <a href="?t=contributors">Rodoslovci</a>.' },
      { text: 'Opozorilo! Hrvatski rodoslovni indeks je informativnega značaja. Hrvaško rodoslovno društvo »Pavao Ritter Vitezović« se odreka vsake odgovornosti za pravilnost posredovanih podatkov. Društvo je prostovoljna zveza posameznikov, ki razvijajo skupen vir poznavanja podatkov iz matičnih registrov in drugih pisnih in ustnih virov. Struktura društva omogoča, da vsak, ki ima svojo zbirko rodoslovnih podatkov, to prispeva skupni kumulativni zbirki in indeksu. Za pravilnost podatkov ne more jamčiti noben posameznik, ki je prispeval podatke v indeks, prav tako ne Hrvaško rodoslovno društvo.', warning: true },
      { text: 'Če imate lastno rodovnikovo podatkovno zbirko in bi se obstoječim sodelavcem radi pridružili z rezultati svojega dela, pošljite svojo datoteko GEDCOM (brez podatkov o živečih osebah) po <a href="mailto:rodoslovlje@rodoslovlje.hr">e-pošti</a> administratorju.' },
    ],
    hr: [
      { text: '<strong>Hrvatski rodoslovni indeks</strong> arhivska je zbirka podataka o rođenima, vjenčanima i umrlima u Hrvatskoj, koja nastaje iz zbirki pojedinih rodoslovaca od samih početaka rada društva. U njoj možemo tražiti imena i prezimena osoba koje istražujemo kako bismo saznali je li ih netko drugi već otkrio i opisao. Osnovni indeks sadrži, osim osobnih imena, datume i mjesta rođenja, vjenčanja i smrti te prezime davatelja podataka, što istraživaču omogućuje daljnji kontakt, naznačuje smjer i često uopće omogućuje istraživanje u posredno otkrivenom župnom arhivu. Kontaktni podaci davatelja nisu objavljeni, ali do njih neće biti teško doći putem <a href="https://www.rodoslovje.hr" target="_blank" rel="noopener">Hrvatskog rodoslovnog društva</a>.' },
      { text: 'Glavni kartica <strong>Pretraga</strong> vraća rezultate upita iz svih dijelova zbirke: rođenih, vjenčanih i umrlih povijesnih osoba u Hrvatskoj. Tražilica omogućuje točnu ili približnu pretragu po svim poljima, kao i pretragu samo zapisa s poveznicom na izvorne dokumente (na <a href="https://www.familysearch.org/en/search/collection/2040054" target="_blank" rel="noopener">Croatia, Church Books, 1516-1994</a> na FamilySearch.org (trebate se prijaviti, besplatno)).' },
      { text: 'Dodatne kartice <strong>Rođenje</strong>, <strong>Obitelj</strong> i <strong>Smrt</strong> omogućuju pretragu po pojedinoj vrsti zapisa. Dostupna su sva polja: ime, prezime, datum i mjesto događaja te prezime rodoslovca-davatelja podataka.' },
      { text: 'Indeks obitelji uključuje i roditelje koji se nikada nisu vjenčali ili čak nikada nisu živjeli zajedno, što može biti dragocjena informacija za potomke ili osobe koje traže podatke. Za svaku obitelj vidljiv je i broj djece. Iza broja skriva se popis dječjih imena s godinom rođenja (gdje taj podatak postoji).' },
      { text: 'Rezultati upita mogu se sortirati po bilo kojem stupcu. Za potpuni pregled, prozor za pretragu može se sakriti. Moguć je izvoz rezultata u obliku CSV datoteke. Za strane korisnike indeksa stranica je dostupna i na engleskom.' },
      { text: 'Popis prezimena, imena, datuma i mjesta rođenja, vjenčanja i smrti napravljen je iz objedinjene datoteke u koju su rezultate svoga rada pridonijeli brojni rodoslovci navedeni na stranici <a href="?t=contributors">Rodoslovci</a>.' },
      { text: 'Upozorenje! Hrvatski rodoslovni indeks isključivo je informativnog karaktera. Hrvatsko rodoslovno društvo odriče se svake odgovornosti za točnost dostavljenih podataka. Društvo je dobrovoljno udruženje pojedinaca koji razvijaju zajednički izvor poznavanja podataka iz matičnih knjiga i drugih pisanih i usmenih izvora. Struktura društva omogućuje svakome tko ima vlastitu zbirku rodoslovnih podataka da je pridonese zajedničkoj kumulativnoj zbirci i indeksu. Za točnost podataka ne može jamčiti ni jedan pojedinac koji je pridonio podatke u indeks, kao ni Hrvatsko rodoslovno društvo.', warning: true },
      { text: 'Ako imate vlastito obiteljsko stablo u obliku baze podataka i željeli biste se pridružiti postojećim rodoslovcima s rezultatima svojega rada, pošaljite svoju GEDCOM datoteku (bez podataka o živim osobama) <a href="mailto:rodoslovlje@rodoslovlje.hr">e-poštom</a> administratoru.' },
    ],
    hu: [
      { text: '<strong>A Horvát Genealógiai Index</strong> születési, házassági és halálozási adatok archív gyűjteménye Horvátországból, amely az egyes genealógusok gyűjteményeiből épül fel a társaság megalakulása óta. Benne kereshetjük azoknak a személyeknek nevét és vezetéknevét, akiket kutatunk, hogy megtudjuk, már valaki más felfedezte és leírta-e őket. Az alapindex a személyneveken kívül a születési, házassági és halálozási dátumokat és helyszíneket, valamint az adatszolgáltató vezetéknevét tartalmazza, ami lehetővé teszi a kutató számára a további kapcsolatfelvételt, megmutatja az irányt, és sokszor lehetővé teszi a közvetve felfedezett plébánián való kutatást. Az adományozók elérhetőségei nem kerülnek közzétételre, de nem lesz nehéz eljutni hozzájuk a <a href="https://www.rodoslovlje.hr" target="_blank" rel="noopener">Horvát Genealógiai Társaságon</a> keresztül.' },
      { text: 'A fő <strong>Keresés</strong> lap a gyűjtemény minden részéből visszaadja a lekérdezés eredményeit: Horvátországban élt történelmi személyek születési, házassági és halálozási adatait. A keresőmotor lehetővé teszi a pontos vagy közelítő keresést az összes mezőben, valamint csak a forrásokhoz mutató hivatkozással rendelkező rekordok keresését (a <a href="https://www.familysearch.org/en/search/collection/2040054" target="_blank" rel="noopener">Croatia, Church Books, 1516-1994</a> FamilySearch.org oldalon (bejelentkezés szükséges, ingyenes)).' },
      { text: 'A további <strong>Születés</strong>, <strong>Család</strong> és <strong>Halál</strong> lapok lehetővé teszik a keresést adott rekordtípusok szerint. Ismét minden mező elérhető: utónév, vezetéknév, az esemény dátuma és helyszíne, valamint az adatokat szolgáltató genealógus vezetékneve.' },
      { text: 'A családindex olyan szülőket is tartalmaz, akik soha nem házasodtak össze, vagy akár soha nem is éltek együtt, ami értékes információ lehet a leszármazottak vagy az információt keresők számára. Minden családnál látható a gyermekek száma is. A szám mögött a gyermekek neveinek listája rejtőzik születési évükkel együtt (ahol ez az adat rendelkezésre áll).' },
      { text: 'A lekérdezés eredményei bármely oszlop szerint rendezhetők. A teljes áttekintéshez a keresőablak elrejthető. Az eredmények CSV fájlként exportálhatók. Az index külföldi felhasználói számára az oldal angolul is elérhető.' },
      { text: 'A születési, házassági és halálozási vezetéknevek, utónevek, dátumok és helyszínek listája egy összesített fájlból készült, amelyhez sok genealógus járult hozzá munkájának eredményeivel; ők a <a href="?t=contributors">Genealógusok</a> oldalon találhatók.' },
      { text: 'Figyelmeztetés! A Horvát Genealógiai Index kizárólag tájékoztató jellegű. A „Pavao Ritter Vitezović" Horvát Genealógiai Társaság elhárít minden felelősséget a benyújtott adatok pontosságáért. A társaság olyan egyének önkéntes egyesülete, akik az anyakönyvekből és más írott és szóbeli forrásokból származó adatok közös tudásforrását fejlesztik. A társaság felépítése lehetővé teszi, hogy mindenki, akinek saját genealógiai adatgyűjteménye van, azt a közös kumulatív gyűjteményhez és indexhez hozzáadja. Az adatok pontosságáért sem az indexhez adatokat hozzájáruló egyén, sem a Horvát Genealógiai Társaság nem vállal felelősséget.', warning: true },
      { text: 'Ha saját családfáját adatbázis formájában tárolja, és szeretne csatlakozni a meglévő genealógusokhoz munkája eredményeivel, küldje GEDCOM fájlját (élő személyek adatai nélkül) <a href="mailto:rodoslovlje@rodoslovlje.hr">e-mailben</a> a rendszergazdának.' },
    ],
    de: [
      { text: '<strong>Der Kroatische Genealogische Index</strong> ist eine Archivsammlung von Daten über Geburten, Heiraten und Sterbefälle in Kroatien, die seit den Anfängen der Gesellschaft aus den Sammlungen einzelner Genealogen entstanden ist. Darin können wir nach Namen und Nachnamen der Personen suchen, die wir erforschen, um herauszufinden, ob sie bereits jemand anderes entdeckt und beschrieben hat. Der Grundindex enthält neben Personennamen auch Daten und Orte von Geburten, Heiraten und Todesfällen sowie den Nachnamen des Datenlieferanten, was dem Forscher weiteren Kontakt ermöglicht, die Richtung anzeigt und oft die Recherche in einer indirekt entdeckten Pfarrei ermöglicht. Die Kontaktdaten der Spender werden nicht veröffentlicht, aber es wird nicht schwer sein, über die <a href="https://www.rodoslovlje.hr" target="_blank" rel="noopener">Kroatische Genealogische Gesellschaft</a> an sie zu gelangen.' },
      { text: 'Die Hauptregisterkarte <strong>Suche</strong> gibt Abfrageergebnisse aus allen Teilen der Sammlung zurück: Geburten, Heiraten und Sterbefälle historischer Persönlichkeiten in Kroatien. Die Suchmaschine ermöglicht exakte oder ungefähre Suchen in allen Feldern sowie die Suche nur nach Einträgen mit einem Link zu den Quelldokumenten (auf <a href="https://www.familysearch.org/en/search/collection/2040054" target="_blank" rel="noopener">Croatia, Church Books, 1516-1994</a> auf FamilySearch.org (Anmeldung erforderlich, kostenlos)).' },
      { text: 'Die zusätzlichen Registerkarten <strong>Geburt</strong>, <strong>Familie</strong> und <strong>Tod</strong> ermöglichen die Suche nach bestimmten Eintragstypen. Wiederum sind alle Felder verfügbar: Name, Nachname, Datum und Ort des Ereignisses sowie der Nachname des Genealogen-Lieferanten dieser Daten.' },
      { text: 'Der Familienindex enthält auch Eltern, die nie geheiratet haben oder nie zusammengelebt haben, was für Nachkommen oder Informationssuchende wertvolle Informationen sein können. Für jede Familie ist auch die Anzahl der Kinder sichtbar. Hinter der Zahl verbirgt sich eine Liste der Kindernamen mit dem Geburtsjahr (wo diese Daten verfügbar sind).' },
      { text: 'Die Abfrageergebnisse können nach beliebiger Spalte sortiert werden. Für eine vollständige Ansicht kann das Abfragefenster ausgeblendet werden. Es ist möglich, die Ergebnisse als CSV-Datei zu exportieren. Für ausländische Nutzer des Index ist die Seite auch auf Englisch verfügbar.' },
      { text: 'Die Liste der Nachnamen, Vornamen, Daten und Orte von Geburten, Heiraten und Sterbefällen stammt aus einer zusammengeführten Datei, zu der viele Genealogen, die auf der Seite <a href="?t=contributors">Genealogen</a> aufgeführt sind, die Ergebnisse ihrer Arbeit beigesteuert haben.' },
      { text: 'Warnung! Der Kroatische Genealogische Index dient nur zu Informationszwecken. Die Kroatische Genealogische Gesellschaft „Pavao Ritter Vitezović" lehnt jede Verantwortung für die Richtigkeit der übermittelten Daten ab. Die Gesellschaft ist ein freiwilliger Zusammenschluss von Einzelpersonen, die eine gemeinsame Wissensquelle für Daten aus Registern und anderen schriftlichen und mündlichen Quellen entwickeln. Die Struktur der Gesellschaft ermöglicht es jedem, der eine eigene Sammlung genealogischer Daten hat, diese zur gemeinsamen kumulativen Sammlung und zum Index beizutragen. Keine Person, die Daten zum Index beigetragen hat, noch die Kroatische Genealogische Gesellschaft kann die Richtigkeit der Daten garantieren.', warning: true },
      { text: 'Wenn Sie Ihren eigenen Stammbaum in Form einer Datenbank haben und sich den bestehenden Genealogen mit den Ergebnissen Ihrer Arbeit anschließen möchten, senden Sie Ihre GEDCOM-Datei (ohne Daten über lebende Personen) per <a href="mailto:rodoslovlje@rodoslovlje.hr">E-Mail</a> an den Administrator.' },
    ],
    it: [
      { text: '<strong>L\'Indice genealogico croato</strong> è una raccolta archivistica di dati su nascite, matrimoni e morti in Croazia, creata dalle collezioni di singoli genealogisti fin dall\'inizio delle attività della società. In esso possiamo cercare i nomi e i cognomi delle persone che stiamo ricercando per scoprire se qualcun altro le ha già individuate e descritte. L\'indice di base contiene, oltre ai nomi personali, le date e i luoghi di nascita, matrimonio e morte, nonché il cognome del fornitore dei dati, il che permette al ricercatore di stabilire ulteriori contatti, indica la direzione e spesso rende possibile la ricerca nella parrocchia indirettamente scoperta. I dati di contatto dei donatori non sono pubblicati, ma non sarà difficile raggiungerli tramite la <a href="https://www.rodoslovlje.hr" target="_blank" rel="noopener">Società genealogica croata</a>.' },
      { text: 'La scheda principale <strong>Ricerca</strong> restituisce i risultati della query da tutte le parti della collezione: nascite, matrimoni e morti di figure storiche in Croazia. Il motore di ricerca consente ricerche esatte o approssimate in tutti i campi, nonché la ricerca solo di record con un collegamento ai documenti originali (su <a href="https://www.familysearch.org/en/search/collection/2040054" target="_blank" rel="noopener">Croatia, Church Books, 1516-1994</a> su FamilySearch.org (accesso richiesto, gratuito)).' },
      { text: 'Le schede aggiuntive <strong>Nascita</strong>, <strong>Famiglia</strong> e <strong>Morte</strong> consentono la ricerca per tipo specifico di record. Anche qui sono disponibili tutti i campi: nome, cognome, data e luogo dell\'evento e il cognome del genealogista fornitore dei dati.' },
      { text: 'L\'indice delle famiglie include anche i genitori che non si sono mai sposati o che non hanno mai vissuto insieme, il che può essere un\'informazione preziosa per i discendenti o per chi cerca informazioni. Per ogni famiglia è inoltre visibile il numero di figli. Dietro il numero è nascosto un elenco dei nomi dei figli con l\'anno di nascita (ove tale dato sia disponibile).' },
      { text: 'I risultati della query possono essere ordinati per qualsiasi colonna. Per una visualizzazione completa, è possibile nascondere la finestra di ricerca. È possibile esportare i risultati in formato CSV. Per gli utenti stranieri dell\'indice, il sito è disponibile anche in inglese.' },
      { text: 'L\'elenco di cognomi, nomi, date e luoghi di nascita, matrimonio e morte è ricavato da un file unificato a cui molti genealogisti, elencati nella pagina <a href="?t=contributors">Genealogisti</a>, hanno contribuito con i risultati del loro lavoro.' },
      { text: 'Avvertenza! L\'Indice genealogico croato ha carattere informativo. La Società genealogica croata "Pavao Ritter Vitezović" declina ogni responsabilità per l\'accuratezza dei dati forniti. La società è un\'associazione volontaria di individui che sviluppano una fonte comune di conoscenza dei dati provenienti da registri e altre fonti scritte e orali. La struttura della società permette a chiunque disponga di una propria raccolta di dati genealogici di contribuirla alla raccolta cumulativa comune e all\'indice. Nessun individuo che abbia contribuito dati all\'indice, né la Società genealogica croata, può garantire l\'accuratezza dei dati.', warning: true },
      { text: 'Se disponi del tuo albero genealogico sotto forma di database e desideri unirti ai genealogisti esistenti con i risultati del tuo lavoro, invia il tuo file GEDCOM (esclusi i dati sulle persone viventi) per <a href="mailto:rodoslovlje@rodoslovlje.hr">email</a> all\'amministratore.' },
    ],
  },
};

export default siteConfig;
