/**
 * Slovenia site configuration.
 * This is the only file that differs between installations.
 * Fork this file (and the public/ assets) to create a new country site.
 */
const siteConfig = {
  // Branding
  logo:        '/srd-logo.png',
  logoAlt:     'Slovensko rodoslovno društvo',
  societyUrl:  'https://rodoslovje.si',
  indexUrl:    'https://rodoslovje.si/rodoslovni-indeks/',
  contactEmail: 'indeks@rodoslovje.si',

  apiHost: 'indeks-api.rodoslovje.si',

  // Languages shown in the dropdown, ordered alphabetically by language name
  languages: ['de', 'en', 'hr', 'hu', 'it', 'sl'],

  // Preferred language when no saved preference or browser match is found
  defaultLang: 'sl',

  // Per-language overrides: site title and society name
  i18n: {
    en: { site_title: 'Slovenian Genealogical Index',      society_name: 'Slovenian Genealogy Society' },
    sl: { site_title: 'Slovenski rodoslovni indeks',       society_name: 'Slovensko rodoslovno društvo' },
    hr: { site_title: 'Slovenski rodoslovni indeks',       society_name: 'Slovensko rodoslovno društvo' },
    hu: { site_title: 'Szlovén Genealógiai Index',         society_name: 'Szlovén Genealógiai Társaság' },
    de: { site_title: 'Slowenischer Genealogischer Index', society_name: 'Slowenische Genealogische Gesellschaft' },
    it: { site_title: 'Indice genealogico sloveno',        society_name: 'Società genealogica slovena' },
  },

  // Intro paragraphs shown on empty search tabs. Falls back to 'en' for missing languages.
  // Each entry: { text: string (HTML allowed), warning?: true }
  intro: {
    en: [
      { text: '<strong>The Slovenian Genealogical Index</strong> is an archival collection of data on births, marriages and deaths in Slovenia, which has been created from the collections of individual genealogists since the very beginning of the society\'s activities. In it, we can search for the names and surnames of the people we are researching to find out if someone else has already discovered and described them. The basic index contains, in addition to personal names, the dates and places of birth, marriage and death, as well as the surname of the data provider, which allows the researcher to make further contact, indicates the direction and often makes it possible to research in an indirectly discovered parish. The contact information of the donors is not published, but it will not be difficult to get to them through the <a href="https://rodoslovje.si" target="_blank" rel="noopener">Slovenian Genealogy Society</a>.' },
      { text: 'The main <strong>Search</strong> tab returns query results from all parts of the collection: births, marriages, and deaths of historical figures in Slovenia. The search engine allows for exact or approximate searches across all fields, as well as searching only for records with a link to the source documents (on <a href="https://data.matricula-online.eu/en/slovenia/" target="_blank" rel="noopener">Matricula Online</a>).' },
      { text: 'The additional <strong>Birth</strong>, <strong>Family</strong>, and <strong>Death</strong> tabs allow searching by specific record types. Again, all fields are available: name, surname, date and place of the event, and the surname of the genealogist-provider of these data.' },
      { text: 'The family index also includes parents who were never married or even never lived together, which can be valuable information for descendants or information seekers. For each family, you can also see the number of children. Hidden behind the number is a list of the children\'s names with their year of birth (where this data is available).' },
      { text: 'The query results can be sorted by any column. For a full view, the query window can be hidden. It is possible to export the results in the form of a CSV file. For foreign users of the index, the site is also available in English.' },
      { text: 'The list of surnames, names, dates and places of birth, marriage and death is made from a merged file to which many genealogists, listed on the <a href="?t=contributors">Genealogists</a> page, have contributed the results of their work.' },
      { text: 'Warning! The Slovenian Genealogical Index is for informational purposes only. The Slovenian Genealogy Society disclaims any responsibility for the accuracy of the submitted data. The society is a voluntary association of individuals who are developing a common source of knowledge of data from registers and other written and oral sources. The structure of the society allows anyone who has their own collection of genealogical data to contribute it to the common cumulative collection and index. No individual who has contributed data to the index, nor the Slovenian Genealogy Society, can guarantee the accuracy of the data.', warning: true },
      { text: 'If you have your own family tree in the form of a database and would like to join the existing genealogists with the results of your work, please send your GEDCOM file (excluding data on living persons) by <a href="mailto:indeks@rodoslovje.si">email</a> to the administrator.' },
    ],
    sl: [
      { text: '<strong>Slovenski rodoslovni indeks</strong> je arhivska zbirka podatkov o rojenih, poročenih in umrlih na Slovenskem, ki nastaja iz zbirk posameznih rodoslovcev že od samega pričetka delovanja društva. V njej lahko poiščemo imena in priimke oseb, ki jih raziskujemo, da bi ugotovili, če jih je morda odkril in popisal že kdo drug. Osnovni indeks vsebuje poleg osebnih imen, datume in kraje rojstev, porok in smrti ter priimek dajalca podatka, kar iskalcu omogoči nadaljnji stik, nakaže smer in marsikdaj sploh omogoči raziskovanje v posredno odkriti župniji. Kontaktni podatki dajalcev sicer niso objavljeni, vendar do njih ne bo težko priti preko <a href="https://rodoslovje.si" target="_blank" rel="noopener">Slovenskega rodoslovnega društva</a>.' },
      { text: 'Osnovni zavihek <strong>Iskanje</strong> vrne rezultate poizvedbe po vseh delih zbirke: rojenih, poročenih in umrlih zgodovinskih oseb na Slovenskem. Iskalnik omogoča točno ali približno iskanje po vseh poljih, pa tudi iskanje samo zapisov s povezavo do izvornih dokumentov (na <a href="https://data.matricula-online.eu/sl/slovenia/" target="_blank" rel="noopener">Matricula Online</a>).' },
      { text: 'Dodatni zavihki <strong>Rojstvo</strong>, <strong>Družina</strong> in <strong>Smrt</strong> omogočajo iskanje po posameznem tipu zapisov. Ponovno so na voljo vsa polja: ime, priimek, datum in kraj dogodka ter priimek rodoslovca-dajalca teh podatkov.' },
      { text: 'Indeks družin vsebuje tudi starše, ki niso bili nikoli poročeni ali celo nikoli niso živeli skupaj, kar je lahko dragocen podatek za potomce oziroma iskalce informacij. Pri vsaki družini pa vidite tudi število otrok. Za številko pa je skrit seznam imen otrok z letnico rojstva (kjer ta podatek obstaja).' },
      { text: 'Rezultate poizvedbe lahko razvrstite po poljubnem stolpcu. Za polno pregledovanje je mogoče skriti poizvedbeno okno. Možen je izvoz rezultatov v obliki CSV datoteke. Za tuje uporabnike indeksa pa je stran na voljo tudi v angleščini.' },
      { text: 'Spisek priimkov, imen, datumov in krajev rojstva, porok in smrti je narejen iz združene datoteke, v katero so rezultate svojega dela posredovali številni rodoslovci, ki so navedeni na strani <a href="?t=contributors">Rodoslovci</a>.' },
      { text: 'Opozorilo! Slovenski rodoslovni indeks je informativnega značaja. Slovensko rodoslovno društvo se odreka vsakršne odgovornosti za pravilnost posredovanih podatkov. Društvo je prostovoljna povezava posameznikov, ki razvijajo skupen vir poznavanja podatkov iz matičnih registrov in drugih pisnih in ustnih virov. Struktura društva omogoča, da lahko vsak, ki ima svojo zbirko rodoslovnih podatkov, to prispeva v skupno kumulativno zbirko in indeks. Za pravilnost podatkov ne more jamčiti noben posameznik, ki je prispeval podatke v indeks, kot tudi ne Slovensko rodoslovno društvo.', warning: true },
      { text: 'Če imate svoj rodovnik v obliki zbirke podatkov in bi se dosedanjim sodelavcem želeli pridružiti z rezultati svojega dela, svojo GEDCOM datoteko (brez podatkov o še živečih osebah) po <a href="mailto:indeks@rodoslovje.si">e-pošti</a> pošljite administratorju.' },
    ],
    hr: [
      { text: '<strong>Slovenski rodoslovni indeks</strong> arhivska je zbirka podataka o rođenima, vjenčanima i umrlima u Sloveniji, koja nastaje iz zbirki pojedinih rodoslovaca od samih početaka rada društva. U njoj možemo tražiti imena i prezimena osoba koje istražujemo kako bismo saznali je li ih netko drugi već otkrio i opisao. Osnovni indeks sadrži, osim osobnih imena, datume i mjesta rođenja, vjenčanja i smrti te prezime davatelja podataka, što istraživaču omogućuje daljnji kontakt, naznačuje smjer i često uopće omogućuje istraživanje u posredno otkrivenom župnom arhivu. Kontaktni podaci davatelja nisu objavljeni, ali do njih neće biti teško doći putem <a href="https://rodoslovje.si" target="_blank" rel="noopener">Slovenskog rodoslovnog društva</a>.' },
      { text: 'Glavni kartica <strong>Pretraga</strong> vraća rezultate upita iz svih dijelova zbirke: rođenih, vjenčanih i umrlih povijesnih osoba u Sloveniji. Tražilica omogućuje točnu ili približnu pretragu po svim poljima, kao i pretragu samo zapisa s poveznicom na izvorne dokumente (na <a href="https://data.matricula-online.eu/en/slovenia/" target="_blank" rel="noopener">Matricula Online</a>).' },
      { text: 'Dodatne kartice <strong>Rođenje</strong>, <strong>Obitelj</strong> i <strong>Smrt</strong> omogućuju pretragu po pojedinoj vrsti zapisa. Dostupna su sva polja: ime, prezime, datum i mjesto događaja te prezime rodoslovca-davatelja podataka.' },
      { text: 'Indeks obitelji uključuje i roditelje koji se nikada nisu vjenčali ili čak nikada nisu živjeli zajedno, što može biti dragocjena informacija za potomke ili osobe koje traže podatke. Za svaku obitelj vidljiv je i broj djece. Iza broja skriva se popis dječjih imena s godinom rođenja (gdje taj podatak postoji).' },
      { text: 'Rezultati upita mogu se sortirati po bilo kojem stupcu. Za potpuni pregled, prozor za pretragu može se sakriti. Moguć je izvoz rezultata u obliku CSV datoteke. Za strane korisnike indeksa stranica je dostupna i na engleskom.' },
      { text: 'Popis prezimena, imena, datuma i mjesta rođenja, vjenčanja i smrti napravljen je iz objedinjene datoteke u koju su rezultate svoga rada pridonijeli brojni rodoslovci navedeni na stranici <a href="?t=contributors">Rodoslovci</a>.' },
      { text: 'Upozorenje! Slovenski rodoslovni indeks isključivo je informativnog karaktera. Slovensko rodoslovno društvo odriče se svake odgovornosti za točnost dostavljenih podataka. Društvo je dobrovoljno udruženje pojedinaca koji razvijaju zajednički izvor poznavanja podataka iz matičnih knjiga i drugih pisanih i usmenih izvora. Struktura društva omogućuje svakome tko ima vlastitu zbirku rodoslovnih podataka da je pridonese zajedničkoj kumulativnoj zbirci i indeksu. Za točnost podataka ne može jamčiti ni jedan pojedinac koji je pridonio podatke u indeks, kao ni Slovensko rodoslovno društvo.', warning: true },
      { text: 'Ako imate vlastito obiteljsko stablo u obliku baze podataka i željeli biste se pridružiti postojećim rodoslovcima s rezultatima svojega rada, pošaljite svoju GEDCOM datoteku (bez podataka o živim osobama) <a href="mailto:indeks@rodoslovje.si">e-poštom</a> administratoru.' },
    ],
    hu: [
      { text: '<strong>A Szlovén Genealógiai Index</strong> születési, házassági és halálozási adatok archív gyűjteménye Szlovéniából, amely az egyes genealógusok gyűjteményeiből épül fel a társaság megalakulása óta. Benne kereshetjük azoknak a személyeknek nevét és vezetéknevét, akiket kutatunk, hogy megtudjuk, már valaki más felfedezte és leírta-e őket. Az alapindex a személyneveken kívül a születési, házassági és halálozási dátumokat és helyszíneket, valamint az adatszolgáltató vezetéknevét tartalmazza, ami lehetővé teszi a kutató számára a további kapcsolatfelvételt, megmutatja az irányt, és sokszor lehetővé teszi a közvetve felfedezett plébánián való kutatást. Az adományozók elérhetőségei nem kerülnek közzétételre, de nem lesz nehéz eljutni hozzájuk a <a href="https://rodoslovje.si" target="_blank" rel="noopener">Szlovén Genealógiai Társaságon</a> keresztül.' },
      { text: 'A fő <strong>Keresés</strong> lap a gyűjtemény minden részéből visszaadja a lekérdezés eredményeit: Szlovéniában élt történelmi személyek születési, házassági és halálozási adatait. A keresőmotor lehetővé teszi a pontos vagy közelítő keresést az összes mezőben, valamint csak a forrásokhoz mutató hivatkozással rendelkező rekordok keresését (a <a href="https://data.matricula-online.eu/en/slovenia/" target="_blank" rel="noopener">Matricula Online</a> oldalon).' },
      { text: 'A további <strong>Születés</strong>, <strong>Család</strong> és <strong>Halál</strong> lapok lehetővé teszik a keresést adott rekordtípusok szerint. Ismét minden mező elérhető: utónév, vezetéknév, az esemény dátuma és helyszíne, valamint az adatokat szolgáltató genealógus vezetékneve.' },
      { text: 'A családindex olyan szülőket is tartalmaz, akik soha nem házasodtak össze, vagy akár soha nem is éltek együtt, ami értékes információ lehet a leszármazottak vagy az információt keresők számára. Minden családnál látható a gyermekek száma is. A szám mögött a gyermekek neveinek listája rejtőzik születési évükkel együtt (ahol ez az adat rendelkezésre áll).' },
      { text: 'A lekérdezés eredményei bármely oszlop szerint rendezhetők. A teljes áttekintéshez a keresőablak elrejthető. Az eredmények CSV fájlként exportálhatók. Az index külföldi felhasználói számára az oldal angolul is elérhető.' },
      { text: 'A születési, házassági és halálozási vezetéknevek, utónevek, dátumok és helyszínek listája egy összesített fájlból készült, amelyhez sok genealógus járult hozzá munkájának eredményeivel; ők a <a href="?t=contributors">Genealógusok</a> oldalon találhatók.' },
      { text: 'Figyelmeztetés! A Szlovén Genealógiai Index kizárólag tájékoztató jellegű. A Szlovén Genealógiai Társaság elhárít minden felelősséget a benyújtott adatok pontosságáért. A társaság olyan egyének önkéntes egyesülete, akik az anyakönyvekből és más írott és szóbeli forrásokból származó adatok közös tudásforrását fejlesztik. A társaság felépítése lehetővé teszi, hogy mindenki, akinek saját genealógiai adatgyűjteménye van, azt a közös kumulatív gyűjteményhez és indexhez hozzáadja. Az adatok pontosságáért sem az indexhez adatokat hozzájáruló egyén, sem a Szlovén Genealógiai Társaság nem vállal felelősséget.', warning: true },
      { text: 'Ha saját családfáját adatbázis formájában tárolja, és szeretne csatlakozni a meglévő genealógusokhoz munkája eredményeivel, küldje GEDCOM fájlját (élő személyek adatai nélkül) <a href="mailto:indeks@rodoslovje.si">e-mailben</a> a rendszergazdának.' },
    ],
    de: [
      { text: '<strong>Der Slowenische Genealogische Index</strong> ist eine Archivsammlung von Daten über Geburten, Heiraten und Sterbefälle in Slowenien, die seit den Anfängen der Gesellschaft aus den Sammlungen einzelner Genealogen entstanden ist. Darin können wir nach Namen und Nachnamen der Personen suchen, die wir erforschen, um herauszufinden, ob sie bereits jemand anderes entdeckt und beschrieben hat. Der Grundindex enthält neben Personennamen auch Daten und Orte von Geburten, Heiraten und Todesfällen sowie den Nachnamen des Datenlieferanten, was dem Forscher weiteren Kontakt ermöglicht, die Richtung anzeigt und oft die Recherche in einer indirekt entdeckten Pfarrei ermöglicht. Die Kontaktdaten der Spender werden nicht veröffentlicht, aber es wird nicht schwer sein, über die <a href="https://rodoslovje.si" target="_blank" rel="noopener">Slowenische Genealogische Gesellschaft</a> an sie zu gelangen.' },
      { text: 'Die Hauptregisterkarte <strong>Suche</strong> gibt Abfrageergebnisse aus allen Teilen der Sammlung zurück: Geburten, Heiraten und Sterbefälle historischer Persönlichkeiten in Slowenien. Die Suchmaschine ermöglicht exakte oder ungefähre Suchen in allen Feldern sowie die Suche nur nach Einträgen mit einem Link zu den Quelldokumenten (auf <a href="https://data.matricula-online.eu/en/slovenia/" target="_blank" rel="noopener">Matricula Online</a>).' },
      { text: 'Die zusätzlichen Registerkarten <strong>Geburt</strong>, <strong>Familie</strong> und <strong>Tod</strong> ermöglichen die Suche nach bestimmten Eintragstypen. Wiederum sind alle Felder verfügbar: Name, Nachname, Datum und Ort des Ereignisses sowie der Nachname des Genealogen-Lieferanten dieser Daten.' },
      { text: 'Der Familienindex enthält auch Eltern, die nie geheiratet haben oder nie zusammengelebt haben, was für Nachkommen oder Informationssuchende wertvolle Informationen sein können. Für jede Familie ist auch die Anzahl der Kinder sichtbar. Hinter der Zahl verbirgt sich eine Liste der Kindernamen mit dem Geburtsjahr (wo diese Daten verfügbar sind).' },
      { text: 'Die Abfrageergebnisse können nach beliebiger Spalte sortiert werden. Für eine vollständige Ansicht kann das Abfragefenster ausgeblendet werden. Es ist möglich, die Ergebnisse als CSV-Datei zu exportieren. Für ausländische Nutzer des Index ist die Seite auch auf Englisch verfügbar.' },
      { text: 'Die Liste der Nachnamen, Vornamen, Daten und Orte von Geburten, Heiraten und Sterbefällen stammt aus einer zusammengeführten Datei, zu der viele Genealogen, die auf der Seite <a href="?t=contributors">Genealogen</a> aufgeführt sind, die Ergebnisse ihrer Arbeit beigesteuert haben.' },
      { text: 'Warnung! Der Slowenische Genealogische Index dient nur zu Informationszwecken. Die Slowenische Genealogische Gesellschaft lehnt jede Verantwortung für die Richtigkeit der übermittelten Daten ab. Die Gesellschaft ist ein freiwilliger Zusammenschluss von Einzelpersonen, die eine gemeinsame Wissensquelle für Daten aus Registern und anderen schriftlichen und mündlichen Quellen entwickeln. Die Struktur der Gesellschaft ermöglicht es jedem, der eine eigene Sammlung genealogischer Daten hat, diese zur gemeinsamen kumulativen Sammlung und zum Index beizutragen. Keine Person, die Daten zum Index beigetragen hat, noch die Slowenische Genealogische Gesellschaft kann die Richtigkeit der Daten garantieren.', warning: true },
      { text: 'Wenn Sie Ihren eigenen Stammbaum in Form einer Datenbank haben und sich den bestehenden Genealogen mit den Ergebnissen Ihrer Arbeit anschließen möchten, senden Sie Ihre GEDCOM-Datei (ohne Daten über lebende Personen) per <a href="mailto:indeks@rodoslovje.si">E-Mail</a> an den Administrator.' },
    ],
    it: [
      { text: '<strong>L\'Indice genealogico sloveno</strong> è una raccolta archivistica di dati su nascite, matrimoni e morti in Slovenia, creata dalle collezioni di singoli genealogisti fin dall\'inizio delle attività della società. In esso possiamo cercare i nomi e i cognomi delle persone che stiamo ricercando per scoprire se qualcun altro le ha già individuate e descritte. L\'indice di base contiene, oltre ai nomi personali, le date e i luoghi di nascita, matrimonio e morte, nonché il cognome del fornitore dei dati, il che permette al ricercatore di stabilire ulteriori contatti, indica la direzione e spesso rende possibile la ricerca nella parrocchia indirettamente scoperta. I dati di contatto dei donatori non sono pubblicati, ma non sarà difficile raggiungerli tramite la <a href="https://rodoslovje.si" target="_blank" rel="noopener">Società genealogica slovena</a>.' },
      { text: 'La scheda principale <strong>Ricerca</strong> restituisce i risultati della query da tutte le parti della collezione: nascite, matrimoni e morti di figure storiche in Slovenia. Il motore di ricerca consente ricerche esatte o approssimate in tutti i campi, nonché la ricerca solo di record con un collegamento ai documenti originali (su <a href="https://data.matricula-online.eu/en/slovenia/" target="_blank" rel="noopener">Matricula Online</a>).' },
      { text: 'Le schede aggiuntive <strong>Nascita</strong>, <strong>Famiglia</strong> e <strong>Morte</strong> consentono la ricerca per tipo specifico di record. Anche qui sono disponibili tutti i campi: nome, cognome, data e luogo dell\'evento e il cognome del genealogista fornitore dei dati.' },
      { text: 'L\'indice delle famiglie include anche i genitori che non si sono mai sposati o che non hanno mai vissuto insieme, il che può essere un\'informazione preziosa per i discendenti o per chi cerca informazioni. Per ogni famiglia è inoltre visibile il numero di figli. Dietro il numero è nascosto un elenco dei nomi dei figli con l\'anno di nascita (ove tale dato sia disponibile).' },
      { text: 'I risultati della query possono essere ordinati per qualsiasi colonna. Per una visualizzazione completa, è possibile nascondere la finestra di ricerca. È possibile esportare i risultati in formato CSV. Per gli utenti stranieri dell\'indice, il sito è disponibile anche in inglese.' },
      { text: 'L\'elenco di cognomi, nomi, date e luoghi di nascita, matrimonio e morte è ricavato da un file unificato a cui molti genealogisti, elencati nella pagina <a href="?t=contributors">Genealogisti</a>, hanno contribuito con i risultati del loro lavoro.' },
      { text: 'Avvertenza! L\'Indice genealogico sloveno ha carattere informativo. La Società genealogica slovena declina ogni responsabilità per l\'accuratezza dei dati forniti. La società è un\'associazione volontaria di individui che sviluppano una fonte comune di conoscenza dei dati provenienti da registri e altre fonti scritte e orali. La struttura della società permette a chiunque disponga di una propria raccolta di dati genealogici di contribuirla alla raccolta cumulativa comune e all\'indice. Nessun individuo che abbia contribuito dati all\'indice, né la Società genealogica slovena, può garantire l\'accuratezza dei dati.', warning: true },
      { text: 'Se disponi del tuo albero genealogico sotto forma di database e desideri unirti ai genealogisti esistenti con i risultati del tuo lavoro, invia il tuo file GEDCOM (esclusi i dati sulle persone viventi) per <a href="mailto:indeks@rodoslovje.si">email</a> all\'amministratore.' },
    ],
  },
};

export default siteConfig;
