services:
  db:
    image: postgres:16-alpine
    container_name: sgi_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: unless-stopped

  api:
    build: ../../../packages/core/backend
    container_name: sgi_api
    volumes:
      - ../../../data:/app/data
      - ../../../packages/core/tools:/app/tools
      - ../../../packages/core/backend/src:/app/src
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - VIRTUAL_HOST=${SGI_API_HOST}
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=${SGI_API_HOST}
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  default:
    name: caddy_net
    external: true